server:
  port: 80
spring:
  application:
    name: order-zookeeper-service
  cloud:
    zookeeper:
      connect-string: 192.168.81.128:2181

      discovery:
        # zookeeper 目录
        root: "/${spring.application.name}"
        # 不需要注册到 zookeeper  上面
        register: false
