server:
  port: 7000


eureka:
  client:
    #表示是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，所以不需要注册，修改为false。
    register-with-eureka: false
    service-url: "http://${eureka.instance.hostname}:${server.port}/eureka"

  server:
    #关闭注册中心的保护机制，Eureka 会统计15分钟之内心跳失败的比例低于85%将会触发保护机制，不剔除服务提供者，如果关闭服务注册中心将不可用的实例正确剔除
    enable-self-preservation: true
  instance:
    hostname: cloud.eureka7000.com


