server:
  port: 8001
spring:
  application:
    name: payment-consul-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 8
      #      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
      auto-commit: true
      pool-name: MyHikariCP
      connection-test-query: SELECT 1
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-id
        service-name: ${spring.application.name}
        #  默认使用host 域名进行通信访问  ，假如需要使用ip  访问  请设置true  意思就是有限是用ip 进行通信
        prefer-ip-address: true




mybatis:
  mapper-locations: classpath*:/mybatis/mapping/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.kb.demo.cloud.common.entity
